name: html_parser
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  html: ^0.14.0+3
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
